### ISSUE TITLE
Sending xrdb to the background is dangerous

### ISSUE THREAD

**Issue by Airblader** [0X1A/wmm#1]
It appears that wmm currently backgrounds all `exec` commands. For `xrdb`, this can cause problems. See https://wiki.archlinux.org/index.php/X_resources#Parsing_.Xresources

**Comment by 0X1A** [comment]
@Airblader wmm won't do anything unless you tell it to, so you are not obligated to put `xrdb` in the `exec` section. I've also never experienced this before, does this happen when using both `Xdefaults` and `Xresources`?

**Comment by Airblader** [comment]
But as a user of wmm I want it to do what mx xinitrc is supposed to do, including the call to `xrdb`. But wmm right now forces me to background every command. It would probably make sense to let it be up to the user to decide whether a command should be sent to the background.
